
name: Automerge Pull Request
on:
  pull_request_target:
    types:
      - opened
      - synchronize

jobs:
  validate-and-comment:
    runs-on: ubuntu-latest

    steps:   
    # Realiza o checkout seguro do código do PR
    - name: Checkout code from PR (Safe Checkout)
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    # Valida o PR de acordo com as recomendações do CONTRIBUTE.md
    - name: Validate PR
      run: |

        # Obtém a lista de arquivos modificados usando a CLI do GitHub
        files_changed=$(gh api repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files --paginate | jq -r '.[].filename')
    
        # Lista os arquivos modificados para fins de depuração
        echo "Changed files:"
        echo "$files_changed"
        
        # Conta quantos arquivos foram modificados
        NUM_CHANGED_FILES=$(echo "$files_changed" | wc -l)
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Comenta no PR se foi bem-sucedido e adiciona a etiqueta [automerge]
    - name: Comment PR on Success and Add Label [automerge]
      if: success()
      run: |
        REPO_URL=${{ github.event.pull_request.head.repo.html_url }}
        cat <<EOT > message.txt
        Aí sim hein! Seu PR foi aprovado 🥳 
        Segue sua URL:
        \`\`\`
        $REPO_URL
        \`\`\`
        Faremos o merge aqui em breve.

        gh pr comment ${{ github.event.pull_request.number }} --body-file=message.txt
        gh pr edit ${{ github.event.pull_request.number }} --add-label "automerge"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # Realiza o merge do PR, caso o job "validate-and-comment" tenha sido executado com sucesso
  merge:
    runs-on: ubuntu-latest
    needs: validate-and-comment
    
    steps:
    - name: Merge PR
      uses: "pascalgn/automerge-action@v0.16.3"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
